# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: 
  name: hugomods/hugo:exts-0.114.0
  entrypoint: [""]

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - hugo version

# Test job for branches other than master
test:
  script:
    - hugo
  except:
    - master

# Pages job for building and deploying the site on master branch
pages:
  script:
    - hugo --minify
  artifacts:
    paths:
      - public
  only:
    - master