baseURL = "http://localhost:1313/"
languageCode = 'en-us'
title = '.Stat Suite Documentation'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
    # uncomment line below for temporary local development of module
    # or when using a 'theme' as a git submodule
    replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[params]
  title = ".Stat Suite Documentation"  # Set your site title
  logoLinkURL = "/"  # Set a custom URL destination for the top header logo link
  customCSS = ["css/custom.css"]

[params.social]
  gitlab = "sis-cc"
  twitter = "sisccommunity"

[params.flexsearch]
  enable = true
  placeholder = "Search..."


